const $=id=>document.getElementById(id);const space=()=>$('space').value;
async function api(path,body){const r=await fetch(path,{method:body===undefined?'GET':'POST',headers:{'Content-Type':'application/json','X-Trace2Mem-CSRF':'1'},body:body===undefined?undefined:JSON.stringify(body)});if(!r.ok)throw Error(await r.text());return r.json()}
const management=(route,body)=>api('/api/'+route+'?space='+encodeURIComponent(space()),body);
const rpc=(service,method,body)=>api('/trace2mem.v1.'+service+'/'+method,{spaceId:space(),...body});
function action(id,fn){$(id).onclick=async()=>{try{$('notice').style.display='none';$(id).disabled=true;await fn()}catch(e){$('notice').textContent=e.message;$('notice').style.display='block'}finally{$(id).disabled=false}}}
function show(id,v){if(id==='status'){const details=[];if(v.error)details.push(v.error);if(v.configured)details.push('Model configuration saved.');if(v.scheduled)details.push('Compilation queued.');if(v.status)details.push(v.status);if(v.jobStatus)details.push('Compilation: '+v.jobStatus);if(v.accepted!==undefined)details.push(v.accepted+' events accepted');if(v.revision)details.push('Revision '+v.revision.slice(0,8));if(v.lastError)details.push(v.lastError);$(id).textContent=details.join(' · ')||'Workspace ready';return}$(id).textContent=JSON.stringify(v,null,2)}
async function refresh(){const old=space();const spaces=await api('/api/spaces');$('space').replaceChildren(...spaces.map(s=>{const o=document.createElement('option');o.value=s.id;o.textContent=s.name;return o}));if(spaces.some(s=>s.id===old))$('space').value=old;if(space())show('status',await rpc('IngestionService','GetIngestionStatus',{}))}
action('create',async()=>{const s=await api('/api/spaces',{name:$('name').value});await refresh();$('space').value=s.id;await refresh()});action('refresh',refresh);$('space').onchange=()=>refresh();
action('configure',async()=>{await management('model',{provider:$('provider').value,endpoint:$('endpoint').value,model:$('model').value,embedding_model:$('embedding').value,embedding_provider:$('embedding-provider').value,embedding_endpoint:$('embedding-endpoint').value,embedding_project:$('embedding-project').value,embedding_location:$('embedding-location').value,embedding_key:$('embedding-key').value,key:$('key').value});$('key').value='';$('embedding-key').value='';show('status',{configured:true})});
action('import',async()=>{const f=$('file').files[0];if(!f)throw Error('Select a JSONL file');const lines=(await f.text()).split('\n').filter(x=>x.trim());for(let i=0;i<lines.length;i+=64){await rpc('IngestionService','AppendEvents',{events:lines.slice(i,i+64).map(JSON.parse)})}await refresh()});
action('compile',async()=>show('status',await management('compile',{})));action('forget',async()=>{if(confirm('Forget this source and rebuild derived memory?')){show('status',await management('forget',{event_id:$('forget-id').value}))}});
action('search',async()=>show('result',await rpc('MemoryService','Search',{query:$('query').value})));action('index',async()=>show('result',await rpc('MemoryService','ReadFile',{path:'knowledge/index.md'})));action('evidence',async()=>show('result',await rpc('MemoryService','GetEvidence',{eventId:$('evidence-id').value})));action('export',async()=>{const v=await management('export');const url=URL.createObjectURL(new Blob([JSON.stringify(v,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='trace2mem-'+v.revision+'.json';a.click();URL.revokeObjectURL(url)});
action('revisions',async()=>show('admin-result',await management('revisions')));action('usage',async()=>show('admin-result',await management('usage')));action('member',async()=>show('admin-result',await management('members',{subject:$('subject').value,role:$('role').value})));action('token',async()=>show('admin-result',await api('/api/tokens',{scopes:['read']})));
action('evaluate',async()=>show('eval-result',await management('evaluate',{cases:JSON.parse($('cases').value)})));action('candidate',async()=>show('eval-result',await management('candidates',{evaluation_id:$('evaluation-id').value})));action('promote',async()=>{if(confirm('Promote this evaluated candidate for future compilations?'))show('eval-result',await management('candidates',{promote_id:$('candidate-id').value}))});refresh().catch(e=>{show('status',{error:e.message})});
for(const button of document.querySelectorAll('[data-panel]')){button.addEventListener('click',()=>{for(const panel of document.querySelectorAll('.panel'))panel.classList.toggle('active',panel.id==='panel-'+button.dataset.panel);for(const nav of document.querySelectorAll('[data-panel]'))nav.classList.toggle('active',nav===button);$('view-title').textContent=button.querySelector('span').textContent})}
action('ask',async()=>{if(!space())throw Error('Create a memory space and import a source first.');const v=await rpc('MemoryService','GetContext',{query:$('query').value});$('result').textContent=v.synthesis||'No supported answer found in this memory.'});
$('query').addEventListener('keydown',e=>{if(e.key==='Enter')$('ask').click()});
